# Generated by Django 4.1.7 on 2023-03-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
        ('authors', '0001_initial'),
        ('books', '0002_book_owner_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.shelf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
    ]
